name: Health Check

on:
  push:
    branches:
      - main
  # schedule:
  #   - cron: '0 0 * * *'

jobs:
  health_check:
    runs-on: ubuntu-20.04
    steps:
      - name: Check the deployed service
        uses: jtalk/url-health-check-action@v4
        with:
          url: https://full-stack-open-pokedex-51g2.onrender.com/health
          max-attempts: 3
          retry-delay: 5s
          retry-all: true
